cognitedata/cognite-grafana-datasource

package.json
The current build assumes you already have a `dist` folder which is not checked into git.
=> Change build order to work without an existing dist folder

src/datasource.ts, src/partials/query.editor.html
Allowing for aggregations to be used within functions, via the syntax [ID,aggregation,granularity]
For example: 
```  
timeseries{name=~'.*temp.*', function = ([ID] - 32) * 5/9}
timeseries{ function = [ID] - [ID,avg,24h] }
timeseries{ function = [ID,step] - [123456789,step] }
```
=> Improved functions

src/__mocks__/cache.ts, src/cache.ts, src/datasource.ts, src/partials/query.editor.html, src/spec/__snapshots__/datasource.test.ts.snap, src/spec/datasource.test.ts
Adding a cache so that we don't send redundant requests. 
Also changing the dataquery requests to be sent in parallel instead of sequentially
=> Optimizing requests

src/datasource.ts, src/spec/__snapshots__/datasource.test.ts.snap, src/spec/datasource.test.ts, tsconfig.json
Switching to using `templateSrv.replace()` along with `options.scopedVars` for templating.
This allows for things such as [repeated panels or rows](http://docs.grafana.org/reference/templating/#repeating-panels) to function properly
=> Templating fix

src/datasource.ts, src/query_ctrl.ts, src/spec/__snapshots__/datasource.test.ts.snap
Forcing update once we get options for a dropdown, since otherwise it doesn't always get updated and is just empty.
=> Fixing dropdown display

src/__mocks__/cache.ts, src/cache.ts, src/datasource.ts, src/partials/query.editor.html, src/query_ctrl.ts, src/spec/__snapshots__/datasource.test.ts.snap, src/spec/datasource.test.ts, src/types.ts, src/utils.ts
Since we have no need to save all asset timeseries for custom queries, I am adding a cache to store the timeseries separately from the `QueryTarget` object. We still need to keep the timeseries array in `QueryTarget` since `Get Timeseries from Asset` still needs to keep track of which ones are selected. However, when we load in the target object in `query_ctrl` we now also check if we are on the assets tab, if not we can clear that array.
Also choosing to limit `Get Timeseries from Asset` to only fetch the first 100 timeseries since `/dataquery` can only show 100 items, and also because that section really should not be used for that many timeseries. A warning will be shown if not all timeseries can be shown. 
Mostly solves #36, although we may be able to further optimize `QueryTarget` by …
=> Optimizing QueryTarget Object

src/datasource.ts
There is currently a limit for `/dataquery` to only contain 100 items per request, but this should not limit a user
Now checking if a request will contain more than 100 items and if it does, split it up into more requests.
Fixes #48
=> allowing custom queries to return more than 100 timeseries

src/datasource.ts, src/parser.ts, src/spec/__snapshots__/datasource.test.ts.snap, src/utils.ts
now if no label is specified for a custom query, we will just use the name of the last timeseries in the function
=> fixing issue with labels for custom queries

src/datasource.ts, src/types.ts
Adding this now so that we at least have something when we hit the datapoints limit
We may decide to improve on this later - for example, by repeating `/dataquery` calls until we get all the data in
=> Adding warning when we hit the datapoint limit

src/datasource.ts, src/parser.ts, src/spec/__snapshots__/datasource.test.ts.snap, src/spec/datasource.test.ts
Adding more variable support. 
`$Variable` or `[[Variable]]`  can now be used in labels, as well as outside of `timeseries{}` filters in custom queries (this allows you to do things like make a custom text box variable, and then having `timeseries{} $Variable`, thus making the query completely customizable via variables (set `$Variable` to things like ` + 100` or `* 3600`, etc.))
=> Replace variables outside filters

src/partials/config.html, src/plugin.json
Closes #66.
A little tricky because of backwards compatibility issues, since we are introducing a new template variable to the routes (which need a server reload upon any changes), which means that I got to learn about how Go's `template` works.
For any future references, [this is the code Grafana uses to update parts of the url](https://github.com/briangann/grafana/blob/d64971e35b09e13ff95624cadbe11141e2ae27eb/pkg/api/pluginproxy/utils.go#L30-L49).
=> Allowing for the base url to be configured

src/cache.ts, src/datasource.ts, src/spec/__snapshots__/datasource.test.ts.snap, src/spec/datasource.test.ts, src/types.ts, src/utils.ts
Working on #63, and was looking at https://github.com/grafana/grafana/blob/master/public/app/core/services/backend_srv.ts in order to see if Grafana has implemented any type of retrying - but it seems like the retry option that is there is only used for grafana 401 errors.
Either way, I was able to find out that `backendSrv` does support cancelling requests that have the same `requestId` if a newer request is made, so I added in that support. Currently only adding this for `dataquery` requests (using `dashboardId_panelId_targetRefId` as the `requestId`) as most other requests don't really need this functionality. 
This should help to make #63 a bit easier to implement now, since we don't have to worry about cancellation tokens (see my comments there)
=> Adding request cancellation

src/parser/ts/grammar.ne, src/parser/ts/grammar.ts, src/parser/ts/index.ts, src/parser/ts/parser.unit.test.ts
basically new tests should be self explanatory
there was one bug, that didn't allow doing any array filtering.
also as a bonus added support for advanced grafana variables. (it allows variable formatting)
=> fix: array sts server filters

src/partials/annotations.editor.html, src/partials/query.editor.html, src/variable_query_ctrl.tsx
add links to documentation in help sections of:
- synthetic TS query field
- annotations
- variables
=> fix: expand description with a docs links

src/__tests__/__snapshots__/datasource.test.ts.snap, src/cdfDatasource.ts, src/constants.ts, src/datasource.ts, src/parser/ts/index.ts, src/parser/ts/parser.unit.test.ts, src/partials/query.editor.html, src/query_ctrl.ts
Add default values of aggregation and granularity for synthetic timeseries if they are not provided.
=> fix: default values of aggregates in STS

src/__tests__/cdfDatasource.test.ts, src/__tests__/datasource.test.ts, src/cdfDatasource.ts
Custom query: display legend labels as a plain text instead of expression.
Example for query `ts{id=1} + ts{id=2} + 1`:
- user label `{{name}}` will result to `timeseries_name_1 + timeseries_name_2 + 1` label (as it used to work)
- user label `Cool custom name` will result to `Cool custom name` label (since no specific timeseries props referenced)
=> fix(custom-query): properly display pure text labels [CDF-8145]

src/components/queryHelp.tsx, src/parser/ts/index.ts, src/parser/ts/parser.unit.test.ts
this supports `ts{alignment=....}` synthetic timeseries alignment feature together with filters.
previously it only worked if qeury was locked to a specific time series `ts{id=.., alignment=....}`
=> feat: custom query datapoints alignment

.github/workflows/release.yml
this is a new way of releasing plugins to Grafana marketplace
this requires only one manual step in addition, which is a PR to https://github.com/grafana/grafana-plugin-repository
taken from here https://github.com/marcusolsson/grafana-jsonapi-datasource/blob/master/.github/workflows/main.yml
=> chore: github action for release

src/plugin.json
`grafanaVersion` is deprecated now, `grafanaDependency` is requred by the new rules.
grafanaDependency basically makes sure it won't be run on grafana 6.
=> chore: require grafana 7.0.6

src/components/queryEditor.tsx
We lost some capabilities with the recent update.
Not possible to see/input $variables in asset tab. 
Before the fix:
After:
=> fix: variable input in assets tab

CHANGELOG.md, package.json, src/plugin.json
Release patch for assets tab v2.1.1
>  The grafanaDependency in plugin.json is a semver string that defines on what versions of Grafana the plugin can be installed on. Currently, the plugin lists grafanaDependency to be “7.0.6”, which means it can only by installed by those who are running _exactly_ 7.0.6. 
this was fixed manually in DB on Grafana side, but needs to fixed before the next release
=> Release 2.1.1

src/__tests__/cdf.client.test.ts, src/__tests__/datasource.test.ts, src/__tests__/datasource.unit.test.ts, src/cdf/client.ts, src/components/queryEditor.tsx, src/components/resourceSelect.tsx, src/css/query_editor.css, src/datasource.ts, src/types.ts
Enables "latest data point" feature in "timeseries" tab
*REFACTOR:*
Due to the code being too inconveniet for unit testing, I rewrote some logic around variable replacing.
Now all the `variable.replace(str, ...)` login is moved in one place, it happens before any other business logic.
=> feat: time series latest value

src/components/queryEditor.tsx, src/types.ts
Got feedback that tab titles started to be a bit confusing.
How it was before: `timeseries`,`asset`,`custom`,`event`.
This doesn't make sense since first three tabs all working with timeseries.
How it is now:
Might need to improve it even more later.
=> fix: self-explanatory tab names

CHANGELOG.md, src/components/flexibleDataModellingTab.tsx, src/components/variableQueryEditor.tsx, src/constants.ts, src/datasource.ts, src/datasources/FlexibleDataModellingDatasource.ts, src/types.ts, src/utils.ts
* The plugin would fail to fetch time series in case of some null values returned in some rows
* Alternative syntax of graphql supported to pull `items` instead of `node/edge` (added in FDM lately)
* Update variables to make it a config option to return externalId or name instead of internal id which makes it more usable with FDM
**Solution**
Check for null values + additiontal parsing
**Affected Resource types**
FDM, variables
**Changes to datasource JSON model**
N/A
**Has documentation been updated**
No
**Have tests been updated?**
No
**Screenshots and examples**
=> FDM null value bugfix / items + variable support

src/components/configEditor.tsx
We have seen many times that a user insert the URL for API into the config setting named "API URL", even though the sample text (api.cognitedata.com) isn't an URL. 
**Solution**
Rename label from API URL to API Host
**Has documentation been updated**
No
=> Change confusing label for API host

src/plugin.json
validation failed:
```
detail: Write relative paths without leading '.' or '/'. e.g. Instead of './img/file.png' use 'img/file.png'
```
=> Fix invalid screenshot relative paths

renovate.json
we are not receiving the CVE fixes quick enough, as renovate only runs once a month
=> Run renovate more often

CHANGELOG.md, package.json, src/__tests__/datasource.events.unit.test.ts, src/components/annotationsQueryEditor.tsx, src/datasources/EventsDatasource.ts
> Customer reported this issue after upgrading Grafana connector to 4.0.0 on their Grafana environment.
The issue is that activeAtTime filter of Events applies always regardless of on or off for the "Active only" property. 
**Solution**
Had to add some unit tests after they were removed in 4.0.0, and found another bug where annotation query filters also were not propagated properly.
Also added hints/examples panel for the query language used in annotations editor.
Screenshot:
=> [POFSP-222] Fix regressions in events table and annotations query

DEVELOPMENT.md, Dockerfile, README.md, run-cdp.sh
- Dockerfile is not maintained by us anymore, instead, we use one provided by Grafana
- Move documentation outside of the main readme (so it doesn't appear on grafana.com)
=> Remove redundant dockerfile, fix documentation

package.json, src/__mocks__/@grafana/runtime.ts, src/__tests__/connector.test.ts, src/__tests__/datasource.test.ts, src/__tests__/dropdown.test.ts, src/__tests__/extractionPipelinesDatasource.test.ts, src/__tests__/login.test.ts, src/__tests__/metrics.test.ts, src/connector.ts, src/datasource.ts, src/test_utils.ts, yarn.lock
- introduced Fetcher, a simple type with a `fetch()` method, to encapsulate an HTTP client
- since we are mocking the fetcher in the tests, I made it possible to supply a custom one into the initSources method
- resolved incompatibility issue where `@grafana/runtime@^10.3.1` type didn't play well with the ~10.2 (by just updating the dependency)
- resolved deprecation warning in which backendSrv.datasourceRequest should be replaced with backendSrv.fetch, ref https://community.grafana.com/t/how-to-migrate-from-backendsrv-datasourcerequest-to-backendsrv-fetch/58770
=> fix(deprecated-apis): remove backendSrv.datasourceRequest

.gitattributes, CHANGELOG.md, package.json, src/parser/common.ne, src/parser/events-assets/grammar.ts, src/parser/ts/grammar.ts, src/parser/ts/parser.unit.test.ts
In custom queries, we observe that the decimal numbers convert to scientific notation when it is more than 7 decimal places and the query fails.
**Solution**
Use standard grammar from nearley to parse float numbers (supports scientific notation as well as a side effect).
=> fix: scientific notation for numbers in custom query

package.json, src/cdf/types.ts, src/datasources/EventsDatasource.spec.ts, src/datasources/EventsDatasource.ts
Customers complaining that Event data's date fields are represented as integer values rather than in Date format.
**Solution**
Convert Event data's createdTime, lastUpdatedTime, startTime, endTime to Date object
**Affected Resource types**
What resource types has been involved in the change? Events
**Changes to datasource JSON model**
What has been updated in the JSON? Any fields added/removed, possible breaking changes? 
No
**Has documentation been updated**
Yes/No
**Have tests been updated?**
Yes
**Screenshots and examples**
Screenshots and example query if applicable
=> Convert event date fields from integer to date objects

.github/workflows/release.yml
The release flow seems to be failing
**Solution**
Try to bump the go lang to 1.21
**Affected Resource types**
Release
**Changes to datasource JSON model**
NA
**Has documentation been updated**
No
**Have tests been updated?**
No
**Screenshots and examples**
NA
=> fix: Bump go version to 1.21
