cognitedata/cognite-grafana-datasource

- Dockerfile
- README.md
- package.json
Adding a `Dockerfile` and instructions on how to run it out of the box with docker.
> Added dockerfile and docker readme.

- src/datasource.ts
Use the official search api instead of the old prefix search.
> Using official search api

- package.json
- src/datasource.ts
- src/grafana.d.ts
- src/module.ts
- src/partials/query.editor.html
- src/query_ctrl.ts
- src/variable_query_ctrl.tsx
- tsconfig.json
- yarn.lock
- Allowing for variables to be used in the `Root Asset` field
- Small fixes
> Asset integration

- src/annotation_ctrl.ts
- src/datasource.ts
- src/module.ts
- src/partials/annotations.editor.html
- src/partials/query.editor.html
- src/plugin.json
- src/query_ctrl.ts
- src/utils.ts
Allowing for CDP events to be shown as annotations in grafana
> Events Integration

- Jenkinsfile
- jest.config.js
- package.json
- src/__mocks__/app/core/utils/datemath.ts
- src/annotation_ctrl.ts
- src/datasource.ts
- src/query_ctrl.ts
- src/spec/__snapshots__/datasource.test.ts.snap
- src/spec/datasource.test.ts
- src/utils.ts
- tsconfig.json
- yarn.lock
Adding in jest tests and fixing up bugs found while creating the bugs.
> Jest testing

- Jenkinsfile
I think `docker push ${imageName}` will push more than what we actually want.
> Only push commit tag and latest

- package.json
- src/__mocks__/cache.ts
- src/annotation_ctrl.ts
- src/cache.ts
- src/datasource.ts
- src/partials/query.editor.html
- src/query_ctrl.ts
- src/spec/__snapshots__/datasource.test.ts.snap
- src/spec/datasource.test.ts
- src/types.ts
- src/variable_query_ctrl.tsx
- yarn.lock
Adding `@grafana/ui` and `src/types.ts`, and improving typing throughout the code.
Also making more error messages visible.
> Better types and error messages

- src/css/query_editor.css
- src/datasource.ts
- src/partials/config.html
- src/partials/query.editor.html
- src/query_ctrl.ts
- src/spec/__snapshots__/datasource.test.ts.snap
- src/spec/datasource.test.ts
Fixing and changing a few things based off of feedback given by Grafana. 
- Fixes the checkboxes in Select Timeseries from Asset, and adds a select all option
- Changes the pattern used for inputting api-keys, where once the api-key is entered, you must press a reset button to reset it; Also, changed it to test for the project name when a user hits Save and Test.
> V0.0.1 feedback fixes

- yarn.lock
> Upgrading @grafana/ui to remove jquery dependency vulnerability

- Dockerfile
Updating the base image to 6.4.4
> Update grafana to 6.4.4

- src/cdfDatasource.ts
- src/constants.ts
- src/datasource.ts
- src/partials/query.editor.html
- src/query_ctrl.ts
- src/types.ts
> fix: per datapoint error handling

- package.json
- src/__tests__/cdfDatasource.test.ts
- src/__tests__/datasource.test.ts
- src/cdfDatasource.ts
- src/datasource.ts
- src/parser/ts/index.ts
- yarn.lock
Now it shows the actual error message instead.
- also some refactor
- introduced a bug here https://github.com/cognitedata/cognite-grafana-datasource/pull/125 Added tests and fixed it now
- upraded prettier since it didn't work with?.optional.?chaining
> fix: misleading error message in custom query [CDF-6622] [CDF-7537]

- src/__tests__/__snapshots__/dropdown.test.ts.snap
- src/__tests__/datasource.test.ts
- src/cdf/client.ts
- src/components/queryEditor.tsx
- src/components/resourceSelect.tsx
- src/css/query_editor.css
- src/datasource.ts
- src/types.ts
- tsconfig.json
I cannot say I am happy with the code, but I didn't find any better abstraction to make ui work the same way.
There are few different cases, and this is covering them at least, tested manually.
> feat: timeseries external ids

- src/__tests__/cdf.client.test.ts
- src/__tests__/datasource.test.ts
- src/cdf/client.ts
- src/cdf/types.ts
- src/components/queryEditor.tsx
- src/components/queryHelp.tsx
- src/components/variableQueryEditor.tsx
- src/constants.ts
- src/css/common.css
- src/css/query_editor.css
- src/datasource.ts
- src/partials/annotations.editor.html
- src/types.ts
> feat: event table [CDF-6926]

- src/__tests__/connector.test.ts
- src/components/configEditor.tsx
- src/connector.ts
- src/constants.ts
- src/datasource.ts
- src/plugin.json
- src/types.ts
> feat: OAuth2.0 client credentials grant flow

- .github/CODEOWNERS
- .github/pull_request_template.md
Adding a template for the PRs to make review process smoother
Also updated codeowners
> Add PR template

- CHANGELOG.md
> Update CHANGELOG.md v3.0.0

- src/datasources/FlexibleDataModellingDatasource.ts
Quick bug (one line) fix around table view which was empty.
> Fix broken table data view

- src/__tests__/datasource.test.ts
- src/__tests__/extractionPipelinesDatasource.test.ts
- src/appEventHandler.ts
- src/components/queryEditor.tsx
Update implementation after grafana review
> fix : use event bus from @grafana/data, remove SystemJS runtime

- renovate.json
Renovate bot is being too spammy now, changing the setup to make it run less often.
> Tweak renovate options

- renovate.json
we are getting a lot of "spam" in this repo, this hopefully auto-resolves most of renovate PRs
Setting is taken from here: https://cognitedata.atlassian.net/wiki/spaces/SEC/pages/3883467032/Renovate+Configuration
> Enable renovate to auto-merge minor version changes

- CHANGELOG.md
- package.json
- src/parser/common.ne
- src/parser/events-assets/grammar.ts
- src/parser/ts/grammar.ts
- src/parser/ts/parser.unit.test.ts
Issue: https://cognitedata.atlassian.net/browse/POFSP-471
🟢 🟢 🟢 
PR tests added 🚀
> fix: performance issue with parser
